export const PLANS = {
  starter: {
    id: 'starter',
    label: 'Starter',
    basePrice: 35,
    minPrice: 25,
    maxPrice: 70,
    coveragePercent: 50,
    maxWeeklyPayout: 1500,
    color: '#6B7280',
    gradient: 'from-gray-600 to-gray-700',
    example: 'Rain stops you? Get ₹420.',
    exampleAmount: 420,
  },
  standard: {
    id: 'standard',
    label: 'Standard',
    basePrice: 65,
    minPrice: 45,
    maxPrice: 130,
    coveragePercent: 70,
    maxWeeklyPayout: 2500,
    color: '#3B82F6',
    gradient: 'from-blue-600 to-blue-700',
    popular: true,
    example: 'Rain stops you? Get ₹588.',
    exampleAmount: 588,
  },
  shield: {
    id: 'shield',
    label: 'Shield',
    basePrice: 99,
    minPrice: 70,
    maxPrice: 200,
    coveragePercent: 90,
    maxWeeklyPayout: 3500,
    color: '#F59E0B',
    gradient: 'from-amber-500 to-amber-600',
    example: 'Rain stops you? Get ₹756.',
    exampleAmount: 756,
  },
} as const

export type PlanId = keyof typeof PLANS
